# Generated by Django 6.0.2 on 2026-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/post/images/default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to='media/'),
        ),
    ]
