# Generated by Django 6.0.2 on 2026-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media\\post\\images\\default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to='avatars/'),
        ),
    ]
