# Generated by Django 6.0.2 on 2026-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_verified_and_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
