# Generated by Django 6.0.2 on 2026-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to='avatars/'),
        ),
    ]
