# Generated by Django 6.0.2 on 2026-04-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_is_verified_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blue_badge_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BlueBadgePurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tran_id", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="initiated",
                        max_length=16,
                    ),
                ),
                ("val_id", models.CharField(blank=True, max_length=128, null=True)),
                ("gateway_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blue_badge_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]

